// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzksPKwkxmEJx3WNKG6ym_L_KLKiJc3aI',
    appId: '1:993341139790:web:15706b5ed63eb3ebce0c1f',
    messagingSenderId: '993341139790',
    projectId: 'riteway-f9e82',
    authDomain: 'riteway-f9e82.firebaseapp.com',
    databaseURL: 'https://riteway-f9e82-default-rtdb.firebaseio.com',
    storageBucket: 'riteway-f9e82.appspot.com',
    measurementId: 'G-1QP1DGDC5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDO1m4zGClB7xwrq9niW76kB4mVU7hSg',
    appId: '1:993341139790:android:3f6e50c001f05a00ce0c1f',
    messagingSenderId: '993341139790',
    projectId: 'riteway-f9e82',
    databaseURL: 'https://riteway-f9e82-default-rtdb.firebaseio.com',
    storageBucket: 'riteway-f9e82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATL4LdbpWO3sa0T7A4swhxu7x78q4t6S8',
    appId: '1:993341139790:ios:c13167d09719aa5cce0c1f',
    messagingSenderId: '993341139790',
    projectId: 'riteway-f9e82',
    databaseURL: 'https://riteway-f9e82-default-rtdb.firebaseio.com',
    storageBucket: 'riteway-f9e82.appspot.com',
    iosClientId: '993341139790-61vkt2mov2l9kjrubftkiiibtcfpt5s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.riteway',
  );
}
